name: feggy_sizer
description: A bunch of sizer utilities for feggy|flutter.
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_sizer
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
