name: feggy_network
description: A bunch of network utilities for feggy|flutter
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_network
version: 1.0.1

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  fpdart: ^1.1.0
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

  #internal
  feggy_exception: ^1.0.0

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
