name: feggy_core
description: A bunch of core utilities for flutter.
version: 1.0.12
repository: https://github.com/fegno/feggy/tree/main/apps/feggy_core

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #* State Management
  flutter_bloc: ^9.0.0

  #* Data Class
  freezed_annotation: ^2.4.4

  #* Network
  dio: ^5.8.0+1

  #* Responsive
  connectivity_plus: ^6.1.3

  #* Cookie Manager
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0

  #* Build Runner
  build_runner: ^2.4.12

  #* Data Class
  freezed: ^2.5.8
