name: feggy_logger
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
