name: feggy_logger
description: An logger for feggy|flutter.
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_logger
version: 1.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
