name: feggy_storage
description: A storage for feggy|flutter.
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_storage
version: 1.0.1

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
# path: ^1.8.0

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
