name: feggy_updater
description: An updater for feggy.
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_updater
version: 1.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
# path: ^1.8.0

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
