name: feggy_extensions
description: A bunch of extensions for feggy | flutter.
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_extensions
version: 1.0.1

environment:
  sdk: ^3.5.4

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
