name: feggy_core
description: A bunch of core utilities for flutter.
version: 1.0.7
repository: https://github.com/fegno/feggy/tree/main/apps/feggy_core

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  feggy_exception: ^1.0.0
  feggy_extensions: ^1.0.0
  feggy_logger: ^1.0.0
  feggy_network: ^1.0.2
  feggy_responsive: ^1.0.0
  feggy_security: ^1.0.0
  feggy_sizer: ^1.0.0
  feggy_storage: ^1.0.0
  feggy_updater: ^1.0.0

  #* State Management
  flutter_bloc: ^8.1.6

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
