name: feggy_exception
description: A bunch of exceptions for feggy | flutter
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_exception
version: 1.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4

dev_dependencies:
  cider: ^0.2.8
  freezed: ^2.5.7
  lints: ^4.0.0
  test: ^1.24.0
