name: feggy_security
description: A bunch of security utilities for feggy|flutter.
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_security
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  encrypt: ^5.0.3

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
