name: feggy_fast_network_image
description: A fast network image for feggy | flutter.
repository: https://github.com/fegno/feggy/tree/main/packages/feggy_fast_network_image
version: 1.0.0

environment:
  sdk: ^3.5.4

# Add regular dependencies here.

dev_dependencies:
  cider: ^0.2.8
  lints: ^4.0.0
  test: ^1.24.0
